#!/bin/sh
################################################################
#AUTHOR
# Nicolas T.
#
#LICENSE
# GPLv2
#
# Tiny System Information tool writen in POSIX shell
################################################################

#========================= Variables
export version='1.0'
# For speed, support UNICODE OFF
export LC='C'
export LANG='C'
#========================= Functions

#memory="$(free -m|grep "Mem"|awk '{print $3 "MB/" $2 "MB"}')"
ambient="$(grep "exec" "$HOME"/.xinitrc | cut -d " " -f "2")"
cpu="$(grep -m 1 "model name" /proc/cpuinfo | cut -d " " -f "5")"
uptime="$(uptime -p|cut -d ',' --output-delimiter=' ' -f '1-' | awk '{print $2 $3 ":" $4 "hr:" $6 "m"}')"

INFO() # Print all info
{
  . /etc/os-release # Load Info
  cat <<EOF
-------------------------
OS      : $PRETTY_NAME
AMBIENT : $ambient
KERNEL  : $(uname -r)
SHELL   : ${SHELL##*/}
CPU     : $cpu
UPTIME  : $uptime
̣̣-------------------------
EOF
}
#========================= Main
INFO
